include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer:
  exclude:
    - '**.g.dart'
  enable-experiment:
    - macros
linter:
  rules:
    public_member_api_docs: false
    flutter_style_todos: false

dart_shield:
  exclude:
    - some/path/to/file/*
  rules:
    - some-rule
  enable-experimental: true
  experimental-rules:
    - some-experimental-rule

