name: dart_shield
description: A security scout for your code.
version: 0.1.0-dev.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.5.0
  analyzer_plugin: ^0.11.3
  args: ^2.5.0
  cli_completion: ^0.5.0
  collection: ^1.18.0
  file: ^7.0.0
  file_system: ^2.0.0
  glob: ^2.1.2
  json_annotation: ^4.9.0
  mason_logger: ^0.2.15
  path: ^1.9.0
  pub_updater: ^0.4.0
  source_span: ^1.10.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  test: ^1.25.5
  very_good_analysis: ^5.1.0

executables:
  dart_shield:
