name: dart_shield
description: Open-source static analysis tool that helps secure your Dart codebase by detecting vulnerabilities before they reach production.
version: 0.1.0-dev.6
repository: https://github.com/yardexx/dart_shield
issue_tracker: https://github.com/yardexx/dart_shield/issues
topics:
  - security
  - analyzer
  - sast
  - tools
  - static-analysis

workspace: 
 - packages/sarif

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  analysis_server_plugin: ^0.3.2
  analyzer: ^10.0.2
  analyzer_plugin: ^0.14.2
  args: ^2.5.0
  checked_yaml: ^2.0.4
  cli_completion: ^0.5.1
  collection: ^1.18.0
  crypto: ^3.0.7
  file: ^7.0.0
  file_system: ^2.0.0
  glob: ^2.1.2
  mason_logger: ^0.3.3
  path: ^1.9.0
  pub_updater: ^0.5.0
  source_span: ^1.10.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.2

dev_dependencies:
  analyzer_testing: ^0.1.0
  build_runner: ^2.10.4
  http: ^1.6.0
  test: ^1.25.5
  test_reflective_loader: ^0.2.0
  toml: ^0.17.0
  very_good_analysis: ^10.0.0

executables:
  dart_shield:
