// ignore_for_file: avoid_print

import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;
import 'package:toml/toml.dart';

import 'utils/regex_sanitizer.dart';

const _gitleaksUrl =
    'https://raw.githubusercontent.com/gitleaks/gitleaks/master/config/gitleaks.toml';

Future<void> main() async {
  print('Fetching Gitleaks rules from $_gitleaksUrl...');
  final response = await http.get(Uri.parse(_gitleaksUrl));

  if (response.statusCode != 200) {
    throw Exception('Failed to load rules: ${response.statusCode}');
  }

  print('Parsing TOML...');
  final document = TomlDocument.parse(response.body);
  final config = document.toMap();
  final rulesList = config['rules'] as List<dynamic>;

  final validRules = <Map<String, dynamic>>[];
  var skippedCount = 0;

  for (final rule in rulesList) {
    if (rule is! Map) continue;

    final id = rule['id'] as String?;
    final description = rule['description'] as String?;
    final rawRegex = rule['regex'] as String?;
    final keywords = (rule['keywords'] as List?)?.cast<String>() ?? [];
    final entropy = (rule['entropy'] as num?)?.toDouble() ?? 0.0;

    if (id == null || description == null || rawRegex == null) {
      print('Skipping incomplete rule: $rule');
      skippedCount++;
      continue;
    }

    // Transpile Regex (Go -> Dart)
    final sanitized = RegexSanitizer.sanitize(rawRegex);

    // Validate Regex compatibility with Dart
    try {
      RegExp(
        sanitized.pattern,
        caseSensitive: sanitized.caseSensitive,
        multiLine: sanitized.multiLine,
      );
    } on Exception catch (_) {
      print('Skipping rule "$id": Incompatible regex ($rawRegex)');
      skippedCount++;
      continue;
    }

    validRules.add({
      'id': id,
      'description': description,
      'pattern': sanitized.pattern,
      'isCaseSensitive': sanitized.caseSensitive,
      'isMultiLine': sanitized.multiLine,
      'keywords': keywords,
      'minEntropy': entropy,
    });
  }

  print(
    'Processed ${rulesList.length} rules. Valid: ${validRules.length}. Skipped: $skippedCount.',
  );

  final jsonContent = const JsonEncoder.withIndent('  ').convert(validRules);

  // 1. Write JSON file (for distribution)
  final jsonFile = File('rules.json');
  await jsonFile.writeAsString(jsonContent);
  print('Generated rules.json');

  // 2. Write Dart file (for embedding)
  final dartFile = File('lib/src/generated/fallback_rules.dart');
  final dartContent =
      '// GENERATED CODE - DO NOT MODIFY BY HAND\n'
          '// Generated by tool/generate_rules.dart\n\n'
          "const String fallbackRulesJson = r'''\n" +
      jsonContent +
      "\n''';\n";

  await dartFile.writeAsString(dartContent);
  print('Generated lib/src/generated/fallback_rules.dart');
}
