name: Dart CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1.6.5
        with:
          sdk: '3.4'

      - name: ⛓ Install Dependencies
        run: dart pub get

      - name: ✂ Format
        run: dart format --output=none --set-exit-if-changed .

      - name: 📊 Analyze
        run: dart analyze --fatal-infos --fatal-warnings .
